#!/usr/bin/env groovy

pipeline {

    agent {
        docker {
            image 'node'
            args '-u root'
        }
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'jenkins/frontend/build.sh'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sh 'jenkins/frontend/deploy.sh'
            }
        }
    }
}
