#!/usr/bin/env groovy

pipeline {

    agent {
        docker {
            image 'node'
            args '-u root'
        }
    }

    stages {
        stage('SetUp') {
            steps {
                echo 'Setting up workspace...'
                sh 'chmod +x jenkins/frontend/*'
            }
        }

        stage('Build') {
            steps {
                echo 'Building...'
                sh 'npm install'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sh './jenkins/frontend/deploy.sh'
            }
        }
    }
}